services:
  nginx:
    container_name: nginx
    image: nginx:1.24
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../.da/tls:/etc/nginx/tls
    ports:
      - 443:443
  backend:
    container_name: backend
    init: true
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ../images/user-icon:/node/images/user-icon
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "app"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
    ports:
      - 33060:3306
    volumes:
      - ./mysql/mysql_init:/docker-entrypoint-initdb.d
      - ../volume/mysql:/var/lib/mysql
      - ./mysql/mysql_migration:/etc/mysql/mysql_migration
      - ./mysql/mysql.conf:/etc/mysql/conf.d/mysql.cnf
